# Generated by Django 4.2.5 on 2023-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalemodel',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
