# Generated by Django 4.2.5 on 2023-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_scalemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
