# Generated by Django 4.2.5 on 2023-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_manufacturer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=320)),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
