name: Test

on:
  push:
    branches: [ "dev","master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run django tests
        run: |
          cd shop
          python manage.py test
      - name: Test coverage report
        run: |
          pip install coverage
          cd shop
          coverage run manage.py test
          coverage report